export { default as Home } from './Home';
export { default as About } from './About';
export { default as Login } from './Login';
export { default as MyPage } from './MyPage';
export { default as Place } from './Place';
export { default as PlaceDetail } from './PlaceDetail';
export { default as PlaceUpload } from './PlaceUpload';
export { default as Story } from './Story';
export { default as StoryDetail } from './StoryDetail';
